import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import React from "react";
import {Separator} from "@/components/ui/separator";
import Header from "@/components/header";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create-p next app',
}

const navs = [
    {
        name: '看板',
        value: ''
    },
    {
        name: '文档',
        value: 'document'
    },
    {
        name: '设置',
        value: 'settings'
    }
]

export default async function ProjectLayout({
                                                children,
                                                params
                                            }: {
    children: React.ReactNode,
    params: any
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <div className={'h-screen flex flex-col'}>
            <Header
                navs={navs}
                parentRoute={`/p/${params.projectId}`}
            />
            <Separator/>
            <main className={'flex-1 py-8 px-4 md:px-8'}>
                {children}
            </main>
        </div>
        </body>
        </html>
    )
}
