import './globals.css'
import type {Metadata} from 'next'
import {getServerSession} from "next-auth";
import {authOptions} from '@/app/api/auth/[...nextauth]/route';
import SessionProviderBox from "@/components/session-provider-box";
import {getProviders, getSession, signIn} from "next-auth/react";
import Sigin from "@/components/sigin";


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
                                             children,
                                         }: {
    children: React.ReactNode
}) {
    return (
        <SessionProviderBox>
            <html lang="en">
            <body>
                {children}
            </body>
            </html>
        </SessionProviderBox>

    )
}
