import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import AuthProvider from "@/context/auth-provider";
import ProviderTheme from "@/context/provider-theme";
import {Toaster} from "@/components/ui/toaster";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create-p next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <AuthProvider>
            <ProviderTheme>
                <body className={inter.className}>
                {children}
                </body>
                <Toaster />
            </ProviderTheme>
        </AuthProvider>
        </html>
    )
}
