import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import React from "react";
import {Separator} from "@/components/ui/separator";
import Header from "@/components/header";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const navs = [
    {
        name: 'Dashboard',
        value: '/'
    },
    {
        name: 'Projects',
        value: '/projects'
    },
    {
        name: 'Todos',
        value: '/teams'
    },
    {
        name: 'Calendar',
        value: '/calendar'
    },
    {
        name: 'Contacts',
        value: '/contacts'
    },
    {
        name: 'Settings',
        value: '/settings'
    }
]

export default async function DashboardLayout({
                                                  children,
                                              }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <div className={'h-screen flex flex-col pt-8'}>
            <Header
                navs={navs}
                parentRoute={'dashboard'}
            />
            <Separator/>
            <main className={'container flex-1 py-8 px-4 md:px-12'}>
                {children}
            </main>
        </div>
        </body>
        </html>
    )
}
