import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import Header from "@/app/dashboard/components/header";
import React from "react";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function DashboardLayout({
                                                  children,
                                              }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Header/>
        <main>
            {children}
        </main>
        </body>
        </html>
    )
}
